/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLocalLogo: typeof import('~icons/local/logo')['default']
    IconLocalMenuVite: typeof import('~icons/local/menu-vite')['default']
    IconLocalMenuVue: typeof import('~icons/local/menu-vue')['default']
    IconLocalMenuVueMenuVue: typeof import('~icons/local/menu-vue-menu-vue')['default']
    IconLocalVite: typeof import('~icons/local/vite')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/common/svg-icon.vue')['default']
  }
}
